# Site settings
title: My Jekyll Testblog
email: sebastian.scarpa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first attempt att creating a jekyllsite.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: thesherps
github_username:  vanillacowboy

# Build settings
markdown: kramdown
